language: node_js
node_js:
- '5.0'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=PhantomJS
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
notifications:
  slack:
    secure: TPnM8aVW0UZARNptA4FYOufTQsj7XBBkealV63dJ8u83qmc23KXTGgIIdLM5QCaiQ182xb+O92SEE9/DqykN8974zEQ9lbShGTNQ5ylglVPQt0tbx3UxFMYCqo/T0yFn5Nss5EWeCPRnEzK+Emq0NbKWaOHnXXHgZN/DwKq0pcjYGjMVIycqoKZnBv1d16gcecdLVWm5FyUR6ht5cMHO+VxtaQjSVo2KhiEnR2LuTnqkg6pxXOMicTnKj99GdEiENDwrMDKdw7R2qBWXsdJPCMx0IG73nxCBstDhsKCFJC25D3R96ckVx42ON4JnTO+ALX4hT3R1ZLldPYQjBZxSmoKVt7+HbLndlQzbWTm2lzxhF7bDxg89X88GQltPPRh0t8L7q1TROp1OmMKsrw/wACYzVmQ/z6sBw6soeAZFS75ABJofZq2fhqQzxw8VVYMVNW8MV+uyVDLI2a2mKbfw9PNvMSCFTEB0DhSWURpxZERCEbJIeZpSnb6o/ZkVrLGuFkuyy0HgAehqrhsDjhKwvcKTP7PhZglHVnRtcWEqQBBRUuetsNignJJs+YcaPrsZ4pWtkM1SkM6ScCUdZ8c9WZ460OcHf12JbXw0ZY9n0joFiq/hh8PtVwKRg5EEhQi3W5GfZ3EgvuVRwszz0uw/+z4IdGFrqcPWs4LAn+F+zwQ=
